Repository ncalc/ncalc, pull requests merged in 2024-05, with the labels that each got.

#134 Fixed `BitwiseXOr` behavior
  src/NCalc/Domain/SerializationVisitor.cs
  test/NCalc.Tests/Fixtures.cs
Labels: requires-review

#166 Fix handling invalid token
  src/NCalc/Parser/LogicalExpressionParser.cs
  test/NCalc.Tests/ExceptionsTests.cs
Labels: bug, help wanted

#160 Add Dependency Injection support
  NCalc.sln
  docs/articles/caching.md
  docs/articles/case_sensitivity.md
  docs/articles/dependency_injection.md
  docs/articles/description.md
  docs/articles/functions.md
  docs/articles/handling_errors.md
  docs/articles/index.md
  docs/articles/parameters.md
  docs/articles/plugins/memory_cache.md
  docs/articles/toc.yml
  src/NCalc.DependencyInjection/Configuration/NCalcServiceBuilder.cs
  src/NCalc.DependencyInjection/Configuration/ServiceCollectionExtensions.cs
  src/NCalc.DependencyInjection/NCalc.DependencyInjection.csproj
  src/NCalc/AdvancedExpression.cs
  src/NCalc/Cache/ILogicalExpressionCache.cs
  src/NCalc/Cache/LogicalExpressionCache.cs
  src/NCalc/Domain/BinaryExpression.cs
  src/NCalc/Domain/Function.cs
  src/NCalc/Domain/Identifier.cs
  src/NCalc/Domain/LogicalExpression.cs
  src/NCalc/Domain/TernaryExpression.cs
  src/NCalc/Domain/UnaryExpression.cs
  src/NCalc/Domain/ValueExpression.cs
  src/NCalc/Expression.cs
  src/NCalc/ExpressionContext.cs
  src/NCalc/ExpressionOptions.cs
  src/NCalc/Factories/ExpressionFactory.cs
  src/NCalc/Factories/IExpressionFactory.cs
  src/NCalc/Factories/ILogicalExpressionFactory.cs
  src/NCalc/Factories/LogicalExpressionFactory.cs
  src/NCalc/Factories/LogicalExpressionFactoryWrapper.cs
  src/NCalc/Handlers/EvaluateFunctionHandler.cs
  src/NCalc/Handlers/EvaluateParameterHandler.cs
  src/NCalc/Helpers/MathHelper.cs
  src/NCalc/NCalc.csproj
  src/NCalc/Parser/LogicalExpressionParser.cs
  src/NCalc/Visitors/Abstractions/IEvaluationVisitor.cs
  src/NCalc/Visitors/Abstractions/ILogicalExpressionVisitor.cs
  src/NCalc/Visitors/Abstractions/IParameterExtractionVisitor.cs
  src/NCalc/Visitors/Abstractions/LogicalExpressionVisitor.cs
  src/NCalc/Visitors/EvaluationVisitor.cs
  src/NCalc/Visitors/ParameterExtractionVisitor.cs
  src/NCalc/Visitors/SerializationVisitor.cs
  src/Plugins/NCalc.MemoryCache/Configuration/LogicalExpressionMemoryCacheOptions.cs
  src/Plugins/NCalc.MemoryCache/Configuration/NCalcBuilderExtensions.cs
  src/Plugins/NCalc.MemoryCache/LogicalExpressionMemoryCache.cs
  src/Plugins/NCalc.MemoryCache/NCalc.MemoryCache.csproj
  test/NCalc.Tests/FactoriesTests.cs
  test/NCalc.Tests/Fixtures/FactoriesFixtures.cs
  test/NCalc.Tests/MemoryCacheTests.cs
  test/NCalc.Tests/NCalc.Tests.csproj
  test/NCalc.Tests/ServiceCollectionExtensionsTests.cs
Labels: enhancement, code quality

#170 Remove `Logical_Expression_From_Cache_Should_Be_The_Same` to work with `dotnet test`
  test/NCalc.Tests/Fixtures/FactoriesFixtures.cs
  test/NCalc.Tests/MemoryCacheTests.cs
Labels: bug, help wanted

#182 Move `Type` logic to `TypeHelper` and improve exception handling.
  CHANGELOG.md
  src/NCalc/Exceptions/NCalcEvaluationException.cs
  src/NCalc/Exceptions/NCalcFunctionNotFoundException.cs
  src/NCalc/Exceptions/NCalcParameterNotDefinedException.cs
  src/NCalc/Expression.cs
  src/NCalc/Helpers/TypeHelper.cs
  src/NCalc/Visitors/Abstractions/ILogicalExpressionVisitor.cs
  src/NCalc/Visitors/Abstractions/LogicalExpressionVisitor.cs
  src/NCalc/Visitors/EvaluationVisitor.cs
  src/NCalc/Visitors/SerializationVisitor.cs
  test/NCalc.Tests/ComparerTests.cs
  test/NCalc.Tests/EvaluationTests.cs
  test/NCalc.Tests/ExceptionsTests.cs
  test/NCalc.Tests/ServiceCollectionExtensionsTests.cs
Labels: code quality
